#!/bin/bash
./mk -o=TARGET_BUILD_VARIANT=user spark n k
~/Android/mkboot/repack-MT65xx.pl -boot ~/Android/KK_iq4404_MT6572/out/target/product/spark/kernel_spark.bin ~/Android/mkboot/boot.img-ramdisk ~/Android/mkboot/boot.img
